#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
    type = 'prompt'
    alignment = 'left'

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        template = '╭'
        foreground = "#7d7d7d"
    [[blocks.segments]]
        type = 'session'
        style = 'diamond'
        leading_diamond = ""
        background = "#472773"
        foreground = "#ffffff"
        trailing_diamond = ""
    [[blocks.segments]]
        type = 'path'
        style = 'diamond'
        background = '#996bc2'
        foreground = '#ffffff'
        template = '{{ .Path }}'
        leading_diamond = ''
        trailing_diamond = ""

        [blocks.segments.properties]
            style = 'full'
    [[blocks.segments]]
    	type = 'git'
    	style = 'diamond'
    	foreground = '#c7c7c7'
    	background = '#ba1414'
        trailing_diamond = ""
    	template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

[[blocks]]
    type = 'prompt'
    alignment = 'right'
     [[blocks.segments]]
     	type = "os"
	style = "diamond"
        leading_diamond = ''
        trailing_diamond = ""
	foreground = "#ffffff"
	background = "#0088cc"
	template = " {{.Icon}}  "
     [[blocks.segments]]
        type = "executiontime"
        style = "diamond"
        leading_diamond = "\ue0b2"
        trailing_diamond = ""
        foreground = "#000000"
        background = "#dbe072"
        template = " {{ .FormattedMs }} "

        [properties]
            threshold = 500
            style = "austin"
            always_enabled = true

    [[blocks.segments]]
        type = "battery"
        style = "diamond"
        leading_diamond = ''
        trailing_diamond = ""
        foreground = "#beffa6"
        background = "#0c9100"
        background_templates = [
            "{{if eq \"Charging\" .State.String}}#40c4ff{{end}}",
            "{{if eq \"Discharging\" .State.String}}#e84925{{end}}",
            "{{if eq \"Full\" .State.String}}#4caf50{{end}}"
        ]
        template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}% "
        [blocks.segments.properties]
            discharging_icon = " "
            charging_icon = " "
            charged_icon = " "

    [[blocks.segments]]
        style = 'diamond'
        type = "time"
        leading_diamond = "\ue0b2"
        trailing_diamond = ""
        foreground = "#ffffff"
        background = "#a376ab"
[[blocks]]
    type = 'prompt'
    alignment = 'left'
    newline = true

    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        template = "╰─"
    	foreground = '#7d7d7d'
	
    [[blocks.segments]]
        type = 'text'
        style = 'plain'
        template = "\u276f"
    	foreground = '#827bbd'
    [transient_prompt]
        foreground_templates = [
          "{{if gt .Code 0}}red{{end}}",
          "{{if eq .Code 0}}magenta{{end}}",
        ]
    	background = 'transparent'
  	template = '❯ '
